package com.google.android.gms.common.api.internal;

import android.support.annotation.NonNull;
import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult.zza;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.TransformedResult;
import java.util.concurrent.TimeUnit;

public final class zzco<R extends Result> extends OptionalPendingResult<R> {
    private final BasePendingResult<R> zzfuo;

    public zzco(PendingResult<R> pendingResult) {
        if (!(pendingResult instanceof BasePendingResult)) {
            throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
        }
        this.zzfuo = (BasePendingResult) pendingResult;
    }

    public final R await() {
        return this.zzfuo.await();
    }

    public final R await(long j, TimeUnit timeUnit) {
        return this.zzfuo.await(j, timeUnit);
    }

    public final void cancel() {
        this.zzfuo.cancel();
    }

    public final R get() {
        if (isDone()) {
            return await(0, TimeUnit.MILLISECONDS);
        }
        throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
    }

    public final boolean isCanceled() {
        return this.zzfuo.isCanceled();
    }

    public final boolean isDone() {
        return this.zzfuo.isReady();
    }

    public final void setResultCallback(ResultCallback<? super R> resultCallback) {
        this.zzfuo.setResultCallback(resultCallback);
    }

    public final void setResultCallback(ResultCallback<? super R> resultCallback, long j, TimeUnit timeUnit) {
        this.zzfuo.setResultCallback(resultCallback, j, timeUnit);
    }

    @NonNull
    public final <S extends Result> TransformedResult<S> then(@NonNull ResultTransform<? super R, ? extends S> resultTransform) {
        return this.zzfuo.then(resultTransform);
    }

    public final void zza(zza zza) {
        this.zzfuo.zza(zza);
    }

    public final Integer zzagv() {
        return this.zzfuo.zzagv();
    }
}
